import { getViewpointStarId } from '../../../shared/viewpoint.js';
import { getAngularProjectionStars } from './filterProjectionStars.js';

export function createDefaultFilterResult(allStars) {
  const safeStars = Array.isArray(allStars) ? allStars : [];
  const angularProjectionStars = getAngularProjectionStars(safeStars, getViewpointStarId());

  return {
    currentFilteredStars: safeStars,
    stellarClassCandidates: safeStars,
    currentConnections: [],
    currentGlobeFilteredStars: angularProjectionStars,
    currentGlobeConnections: [],
    showConstellationBoundaries: false,
    showConstellationNames: false,
    showConstellationOverlay: false,
    showConstellationBoundariesFlag: false,
    showConstellationNamesFlag: false,
    showConstellationOverlayFlag: false,
    globeOpaqueSurface: true,
    enableConnections: false,
    enableIsolationFilter: false,
    enableDensityFilter: false,
    enableIsolationFilterFlag: false,
    enableDensityFilterFlag: false,
    isolation: 5,
    isolationTolerance: 0,
    density: 10,
    densityTopPercent: 10,
    densityBottomPercent: 10,
    densityTolerance: 0,
    densityOpacity: 1.0,
    cloudOpacity: 1.0,
    cloudDensityRadius: 5,
    cloudDensityOpacity: 1.0,
    dustCloudMode: 'density',
    starOpacity: 1.0,
    starNameOpacity: 1.0,
    connectionOpacity: 0.5,
    connectionWidth: 5,
    connectionFade: 1,
    connectionLabelSize: 1,
    constellationLineOpacity: 0.4,
    constellationLineWidth: 1,
    constellationNameOpacity: 0.8,
    planeOpacity: 0.5,
    selectedDustClouds: [],
    minDistance: 0,
    maxDistance: 20,
    showDistanceInLabels: true,
    isolationGridSize: 1,
    densityGridSize: 1,
    showClouds: false,
    showCloudDensity: false,
    showGalacticPlane: false,
    showEclipticPlane: false,
    showCelestialEquator: false,
    showCloudsFlag: false,
    showCloudDensityFlag: false,
    showGalacticPlaneFlag: false,
    showEclipticPlaneFlag: false,
    showCelestialEquatorFlag: false,
    stellarClassStarSizes: {},
    stellarClassLabelSizes: {},
    isolationOverlay: null,
    densityOverlay: null,
    cloudDensityOverlays: [],
    cloudDensitySignature: '',
    cloudDensityRenderSignature: '',
    cloudDensityUpdateRequestId: 0
  };
}
