export function createAppState() {
  return {
    cachedStars: null,
    currentFilteredStars: [],
    currentConnections: [],
    currentGlobeFilteredStars: [],
    currentGlobeConnections: [],
    currentMollweideFilteredStars: [],
    currentMollweideConnections: [],
    selectedStarData: null,
    selectedHighlightTrue: null,
    selectedHighlightGlobe: null,
    selectedHighlightMollweide: null,
    constellationLinesGlobe: [],
    constellationLabelsGlobe: [],
    constellationOverlayGlobe: [],
    constellationLinesMoll: [],
    constellationLabelsMoll: [],
    constellationOverlayMoll: [],
    globeSurfaceSphere: null,
    isolationOverlay: null,
    densityOverlay: null,
    cloudDensityOverlays: [],
    galacticPlaneTrue: null,
    eclipticPlaneTrue: null,
    celestialEquatorTrue: null,
    galacticPlaneGlobe: null,
    eclipticPlaneGlobe: null,
    celestialEquatorGlobe: null,
    galacticPlaneMoll: null,
    eclipticPlaneMoll: null,
    celestialEquatorMoll: null,
    galacticDirectionLabelsTrue: [],
    galacticDirectionLabelsGlobe: [],
    galacticDirectionLabelsMoll: [],
    showConstellationBoundariesFlag: false,
    showConstellationNamesFlag: false,
    showConstellationOverlayFlag: false,
    enableIsolationFilterFlag: false,
    enableDensityFilterFlag: false,
    showCloudsFlag: false,
    showCloudDensityFlag: false,
    showGalacticPlaneFlag: false,
    showEclipticPlaneFlag: false,
    showCelestialEquatorFlag: false,
    presetMaps: {
      starLabelOffsets: new Map(),
      starLabelRotations: new Map(),
      starLabelScales: new Map(),
      constellationLabelOffsets: new Map(),
      galacticLabelOffsets: new Map()
    },
    lineState: {
      removedLineSegments: new Set(),
      hiddenLineKeys: new Set()
    }
  };
}
