import { loadStellarClassData } from './stellarClassData.js';
import { generateStellarClassFilters as scGenerate } from './stellarClassFilter.js';
import { loadConstellationBoundaries, loadConstellationCenters } from './constellationFilter.js';
import { bindAdditionalOpacitySliders } from '../ui/filterUI.js';

let filterForm = null;

export async function setupFilterUI(allStars) {
  filterForm = document.getElementById('filters-form');
  if (!filterForm) {
    console.warn('[setupFilterUI] No #filters-form found in DOM!');
    return;
  }
  await loadStellarClassData();
  scGenerate(allStars);
  const mainLegends = filterForm.querySelectorAll('legend.collapsible');
  mainLegends.forEach(legend => {
    const fc = legend.nextElementSibling;
    if (fc) fc.style.maxHeight = '0px';
    legend.addEventListener('click', () => {
      legend.classList.toggle('active');
      const isActive = legend.classList.contains('active');
      legend.setAttribute('aria-expanded', isActive);
      if (fc) fc.style.maxHeight = isActive ? fc.scrollHeight + 'px' : '0px';
    });
  });
  addConstellationsFieldset();
  addGlobeSurfaceFieldset();
  addPlanesFieldset();
  bindAdditionalOpacitySliders();
  // Clouds fieldset is added in the UI file.
  await loadConstellationBoundaries();
  await loadConstellationCenters();
}

function addConstellationsFieldset() {
  const fs = document.createElement('fieldset');
  const legend = document.createElement('legend');
  legend.classList.add('collapsible');
  legend.textContent = 'Constellations';
  fs.appendChild(legend);
  const contentDiv = document.createElement('div');
  contentDiv.classList.add('filter-content', 'scrollable-category');
  contentDiv.style.maxHeight = '0px';
  legend.addEventListener('click', () => {
    legend.classList.toggle('active');
    const isActive = legend.classList.contains('active');
    legend.setAttribute('aria-expanded', isActive);
    contentDiv.style.maxHeight = isActive ? contentDiv.scrollHeight + 'px' : '0px';
  });
  const boundaryDiv = document.createElement('div');
  boundaryDiv.classList.add('filter-item');
  const boundaryChk = document.createElement('input');
  boundaryChk.type = 'checkbox';
  boundaryChk.id = 'show-constellation-boundaries';
  boundaryChk.name = 'show-constellation-boundaries';
  boundaryChk.checked = true;
  const boundaryLbl = document.createElement('label');
  boundaryLbl.htmlFor = 'show-constellation-boundaries';
  boundaryLbl.textContent = 'Show Constellation Boundaries';
  boundaryDiv.appendChild(boundaryChk);
  boundaryDiv.appendChild(boundaryLbl);
  contentDiv.appendChild(boundaryDiv);
  const namesDiv = document.createElement('div');
  namesDiv.classList.add('filter-item');
  const namesChk = document.createElement('input');
  namesChk.type = 'checkbox';
  namesChk.id = 'show-constellation-names';
  namesChk.name = 'show-constellation-names';
  namesChk.checked = true;
  const namesLbl = document.createElement('label');
  namesLbl.htmlFor = 'show-constellation-names';
  namesLbl.textContent = 'Show Constellation Names';
  namesDiv.appendChild(namesChk);
  namesDiv.appendChild(namesLbl);
  contentDiv.appendChild(namesDiv);
  const overlayDiv = document.createElement('div');
  overlayDiv.classList.add('filter-item');
  const overlayChk = document.createElement('input');
  overlayChk.type = 'checkbox';
  overlayChk.id = 'show-constellation-overlay';
  overlayChk.name = 'show-constellation-overlay';
  overlayChk.checked = false;
  const overlayLbl = document.createElement('label');
  overlayLbl.htmlFor = 'show-constellation-overlay';
  overlayLbl.textContent = 'Show Constellation Overlays';
  overlayDiv.appendChild(overlayChk);
  overlayDiv.appendChild(overlayLbl);
  contentDiv.appendChild(overlayDiv);

  const lineOpDiv = document.createElement('div');
  lineOpDiv.classList.add('filter-item');
  const lineOpLabel = document.createElement('label');
  lineOpLabel.htmlFor = 'constellation-line-opacity-slider';
  lineOpLabel.textContent = 'Line Opacity:';
  const lineOpSlider = document.createElement('input');
  lineOpSlider.type = 'range';
  lineOpSlider.id = 'constellation-line-opacity-slider';
  lineOpSlider.name = 'constellation-line-opacity';
  lineOpSlider.min = '0';
  lineOpSlider.max = '100';
  lineOpSlider.value = '40';
  lineOpSlider.step = '1';
  const lineOpNumber = document.createElement('input');
  lineOpNumber.type = 'number';
  lineOpNumber.id = 'constellation-line-opacity-number';
  lineOpNumber.name = 'constellation-line-opacity';
  lineOpNumber.min = '0';
  lineOpNumber.max = '100';
  lineOpNumber.value = '40';
  lineOpNumber.step = '1';
  const lineOpSpan = document.createElement('span');
  lineOpSpan.id = 'constellation-line-opacity-value';
  lineOpSpan.textContent = '40';
  lineOpDiv.appendChild(lineOpLabel);
  lineOpDiv.appendChild(lineOpSlider);
  lineOpDiv.appendChild(lineOpNumber);
  lineOpDiv.appendChild(lineOpSpan);
  lineOpDiv.appendChild(document.createTextNode('%'));
  contentDiv.appendChild(lineOpDiv);

  const lineWidthDiv = document.createElement('div');
  lineWidthDiv.classList.add('filter-item');
  const lineWidthLabel = document.createElement('label');
  lineWidthLabel.htmlFor = 'constellation-line-width-slider';
  lineWidthLabel.textContent = 'Line Width:';
  const lineWidthSlider = document.createElement('input');
  lineWidthSlider.type = 'range';
  lineWidthSlider.id = 'constellation-line-width-slider';
  lineWidthSlider.name = 'constellation-line-width';
  lineWidthSlider.min = '0.1';
  lineWidthSlider.max = '5';
  lineWidthSlider.value = '1';
  lineWidthSlider.step = '0.1';
  const lineWidthNumber = document.createElement('input');
  lineWidthNumber.type = 'number';
  lineWidthNumber.id = 'constellation-line-width-number';
  lineWidthNumber.name = 'constellation-line-width';
  lineWidthNumber.min = '0.1';
  lineWidthNumber.max = '5';
  lineWidthNumber.value = '1.0';
  lineWidthNumber.step = '0.1';
  const lineWidthSpan = document.createElement('span');
  lineWidthSpan.id = 'constellation-line-width-value';
  lineWidthSpan.textContent = '1.0';
  lineWidthDiv.appendChild(lineWidthLabel);
  lineWidthDiv.appendChild(lineWidthSlider);
  lineWidthDiv.appendChild(lineWidthNumber);
  lineWidthDiv.appendChild(lineWidthSpan);
  lineWidthDiv.appendChild(document.createTextNode('px'));
  contentDiv.appendChild(lineWidthDiv);

  const nameOpDiv = document.createElement('div');
  nameOpDiv.classList.add('filter-item');
  const nameOpLabel = document.createElement('label');
  nameOpLabel.htmlFor = 'constellation-name-opacity-slider';
  nameOpLabel.textContent = 'Name Opacity:';
  const nameOpSlider = document.createElement('input');
  nameOpSlider.type = 'range';
  nameOpSlider.id = 'constellation-name-opacity-slider';
  nameOpSlider.name = 'constellation-name-opacity';
  nameOpSlider.min = '0';
  nameOpSlider.max = '100';
  nameOpSlider.value = '80';
  nameOpSlider.step = '1';
  const nameOpNumber = document.createElement('input');
  nameOpNumber.type = 'number';
  nameOpNumber.id = 'constellation-name-opacity-number';
  nameOpNumber.name = 'constellation-name-opacity';
  nameOpNumber.min = '0';
  nameOpNumber.max = '100';
  nameOpNumber.value = '80';
  nameOpNumber.step = '1';
  const nameOpSpan = document.createElement('span');
  nameOpSpan.id = 'constellation-name-opacity-value';
  nameOpSpan.textContent = '80';
  nameOpDiv.appendChild(nameOpLabel);
  nameOpDiv.appendChild(nameOpSlider);
  nameOpDiv.appendChild(nameOpNumber);
  nameOpDiv.appendChild(nameOpSpan);
  nameOpDiv.appendChild(document.createTextNode('%'));
  contentDiv.appendChild(nameOpDiv);

  const borderWidthDiv = document.createElement('div');
  borderWidthDiv.classList.add('filter-item');
  const borderWidthLabel = document.createElement('label');
  borderWidthLabel.htmlFor = 'mollweide-border-width-slider';
  borderWidthLabel.textContent = 'Border Width:';
  const borderWidthSlider = document.createElement('input');
  borderWidthSlider.type = 'range';
  borderWidthSlider.id = 'mollweide-border-width-slider';
  borderWidthSlider.name = 'mollweide-border-width';
  borderWidthSlider.min = '0.1';
  borderWidthSlider.max = '10';
  borderWidthSlider.value = '1';
  borderWidthSlider.step = '0.1';
  const borderWidthNumber = document.createElement('input');
  borderWidthNumber.type = 'number';
  borderWidthNumber.id = 'mollweide-border-width-number';
  borderWidthNumber.name = 'mollweide-border-width';
  borderWidthNumber.min = '0.1';
  borderWidthNumber.max = '10';
  borderWidthNumber.value = '1.0';
  borderWidthNumber.step = '0.1';
  const borderWidthSpan = document.createElement('span');
  borderWidthSpan.id = 'mollweide-border-width-value';
  borderWidthSpan.textContent = '1.0';
  borderWidthDiv.appendChild(borderWidthLabel);
  borderWidthDiv.appendChild(borderWidthSlider);
  borderWidthDiv.appendChild(borderWidthNumber);
  borderWidthDiv.appendChild(borderWidthSpan);
  borderWidthDiv.appendChild(document.createTextNode('px'));
  contentDiv.appendChild(borderWidthDiv);

  const borderOpacityDiv = document.createElement('div');
  borderOpacityDiv.classList.add('filter-item');
  const borderOpacityLabel = document.createElement('label');
  borderOpacityLabel.htmlFor = 'mollweide-border-opacity-slider';
  borderOpacityLabel.textContent = 'Border Opacity:';
  const borderOpacitySlider = document.createElement('input');
  borderOpacitySlider.type = 'range';
  borderOpacitySlider.id = 'mollweide-border-opacity-slider';
  borderOpacitySlider.name = 'mollweide-border-opacity';
  borderOpacitySlider.min = '0';
  borderOpacitySlider.max = '100';
  borderOpacitySlider.value = '100';
  borderOpacitySlider.step = '1';
  const borderOpacityNumber = document.createElement('input');
  borderOpacityNumber.type = 'number';
  borderOpacityNumber.id = 'mollweide-border-opacity-number';
  borderOpacityNumber.name = 'mollweide-border-opacity';
  borderOpacityNumber.min = '0';
  borderOpacityNumber.max = '100';
  borderOpacityNumber.value = '100';
  borderOpacityNumber.step = '1';
  const borderOpacitySpan = document.createElement('span');
  borderOpacitySpan.id = 'mollweide-border-opacity-value';
  borderOpacitySpan.textContent = '100';
  borderOpacityDiv.appendChild(borderOpacityLabel);
  borderOpacityDiv.appendChild(borderOpacitySlider);
  borderOpacityDiv.appendChild(borderOpacityNumber);
  borderOpacityDiv.appendChild(borderOpacitySpan);
  borderOpacityDiv.appendChild(document.createTextNode('%'));
  contentDiv.appendChild(borderOpacityDiv);

  fs.appendChild(contentDiv);
  filterForm.appendChild(fs);
}

function addGlobeSurfaceFieldset() {
  const fs = document.createElement('fieldset');
  const legend = document.createElement('legend');
  legend.classList.add('collapsible');
  legend.textContent = 'Globe Surface';
  fs.appendChild(legend);
  const contentDiv = document.createElement('div');
  contentDiv.classList.add('filter-content');
  contentDiv.style.maxHeight = '0px';
  legend.addEventListener('click', () => {
    legend.classList.toggle('active');
    const isActive = legend.classList.contains('active');
    legend.setAttribute('aria-expanded', isActive);
    contentDiv.style.maxHeight = isActive ? contentDiv.scrollHeight + 'px' : '0px';
  });
  const surfDiv = document.createElement('div');
  surfDiv.classList.add('filter-item');
  const surfChk = document.createElement('input');
  surfChk.type = 'checkbox';
  surfChk.id = 'globe-opaque-surface';
  surfChk.name = 'globe-opaque-surface';
  surfChk.checked = true;
  const surfLbl = document.createElement('label');
  surfLbl.htmlFor = 'globe-opaque-surface';
  surfLbl.textContent = 'Opaque Globe Surface';
  surfDiv.appendChild(surfChk);
  surfDiv.appendChild(surfLbl);
  contentDiv.appendChild(surfDiv);
  fs.appendChild(contentDiv);
  filterForm.appendChild(fs);
}

function addPlanesFieldset() {
  const fs = document.createElement('fieldset');
  const legend = document.createElement('legend');
  legend.classList.add('collapsible');
  legend.textContent = 'Planes';
  fs.appendChild(legend);

  const contentDiv = document.createElement('div');
  contentDiv.classList.add('filter-content');
  contentDiv.style.maxHeight = '0px';
  legend.addEventListener('click', () => {
    legend.classList.toggle('active');
    const isActive = legend.classList.contains('active');
    legend.setAttribute('aria-expanded', isActive);
    contentDiv.style.maxHeight = isActive ? contentDiv.scrollHeight + 'px' : '0px';
  });

  const galDiv = document.createElement('div');
  galDiv.classList.add('filter-item');
  const galChk = document.createElement('input');
  galChk.type = 'checkbox';
  galChk.id = 'show-galactic-plane';
  galChk.name = 'show-galactic-plane';
  galChk.checked = false;
  const galLbl = document.createElement('label');
  galLbl.htmlFor = 'show-galactic-plane';
  galLbl.textContent = 'Show Galactic Plane';
  galDiv.appendChild(galChk);
  galDiv.appendChild(galLbl);
  contentDiv.appendChild(galDiv);

  const eclDiv = document.createElement('div');
  eclDiv.classList.add('filter-item');
  const eclChk = document.createElement('input');
  eclChk.type = 'checkbox';
  eclChk.id = 'show-ecliptic-plane';
  eclChk.name = 'show-ecliptic-plane';
  eclChk.checked = false;
  const eclLbl = document.createElement('label');
  eclLbl.htmlFor = 'show-ecliptic-plane';
  eclLbl.textContent = 'Show Ecliptic Plane';
  eclDiv.appendChild(eclChk);
  eclDiv.appendChild(eclLbl);
  contentDiv.appendChild(eclDiv);

  const eqDiv = document.createElement('div');
  eqDiv.classList.add('filter-item');
  const eqChk = document.createElement('input');
  eqChk.type = 'checkbox';
  eqChk.id = 'show-celestial-equator';
  eqChk.name = 'show-celestial-equator';
  eqChk.checked = false;
  const eqLbl = document.createElement('label');
  eqLbl.htmlFor = 'show-celestial-equator';
  eqLbl.textContent = 'Show Celestial Equator';
  eqDiv.appendChild(eqChk);
  eqDiv.appendChild(eqLbl);
  contentDiv.appendChild(eqDiv);

  const planeOpDiv = document.createElement('div');
  planeOpDiv.classList.add('filter-item');
  const planeOpLabel = document.createElement('label');
  planeOpLabel.htmlFor = 'plane-opacity-slider';
  planeOpLabel.textContent = 'Plane Opacity:';
  const planeOpSlider = document.createElement('input');
  planeOpSlider.type = 'range';
  planeOpSlider.id = 'plane-opacity-slider';
  planeOpSlider.name = 'plane-opacity';
  planeOpSlider.min = '0';
  planeOpSlider.max = '100';
  planeOpSlider.value = '50';
  planeOpSlider.step = '1';
  const planeOpNumber = document.createElement('input');
  planeOpNumber.type = 'number';
  planeOpNumber.id = 'plane-opacity-number';
  planeOpNumber.name = 'plane-opacity';
  planeOpNumber.min = '0';
  planeOpNumber.max = '100';
  planeOpNumber.value = '50';
  planeOpNumber.step = '1';
  const planeOpSpan = document.createElement('span');
  planeOpSpan.id = 'plane-opacity-value';
  planeOpSpan.textContent = '50';
  planeOpDiv.appendChild(planeOpLabel);
  planeOpDiv.appendChild(planeOpSlider);
  planeOpDiv.appendChild(planeOpNumber);
  planeOpDiv.appendChild(planeOpSpan);
  planeOpDiv.appendChild(document.createTextNode('%'));
  contentDiv.appendChild(planeOpDiv);

  fs.appendChild(contentDiv);
  filterForm.appendChild(fs);
}

export { scGenerate as generateStellarClassFilters };
